import test from 'node:test';
import assert from 'node:assert/strict';
import {questions,tasks,sources} from '../dist/content.js';
import {DAY,defaults,schedule,mockSelection,sameSet,dueCards,dayKey,streak,validateBackup} from '../dist/core.js';
test('bank covers every official task with unique IDs and valid answer indices',()=>{assert.equal(questions.length,new Set(questions.map(q=>q.id)).size);for(const t of Object.keys(tasks))assert.ok(questions.some(q=>q.task===t),t);for(const q of questions){assert.equal(q.options.length,4);assert.ok(q.correct.every(i=>i>=0&&i<4));assert.ok(sources[q.source]);assert.ok(q.front&&q.answer&&q.explanation);}});
test('mock samples 60 unique items with rounded domain weights',()=>{for(let i=0;i<50;i++){const items=mockSelection(questions);assert.equal(items.length,60);assert.equal(new Set(items.map(q=>q.id)).size,60);assert.deepEqual([1,2,3,4,5].map(d=>items.filter(q=>q.domain===d).length),[16,11,12,12,9]);}});
test('recall schedules distinguish relearning from long-term review',()=>{const now=1000000;const again=schedule(null,'again',now),hard=schedule(null,'hard',now),good=schedule(null,'good',now),easy=schedule(null,'easy',now);assert.equal(again.due,now+60000);assert.equal(hard.due,now+600000);assert.equal(good.due,now+DAY);assert.equal(easy.due,now+4*DAY);const second=schedule(good,'good',now+DAY);assert.equal(second.interval,6);const lapse=schedule(second,'again',now+7*DAY);assert.equal(lapse.reps,0);assert.equal(lapse.lapses,1);assert.equal(schedule(lapse,'good',now+7*DAY).interval,1);assert.throws(()=>schedule(null,'bogus'));});
test('ease floor and scheduling ceiling protect repeated ratings',()=>{let card=null;for(let i=0;i<100;i++)card=schedule(card,'again',1000000);assert.equal(card.ease,1.3);for(let i=0;i<100;i++)card=schedule(card,'easy',1000000);assert.ok(card.interval<=36500);assert.ok(card.ease<=3);});
test('multiple-response scoring requires the exact set',()=>{assert.equal(sameSet([1,0],[0,1]),true);assert.equal(sameSet([0],[0,1]),false);assert.equal(sameSet([0,0],[0,1]),false);assert.equal(sameSet([0,1,2],[0,1]),false);});
test('queue prioritizes due reviews and respects daily new/review limits',()=>{const s=defaults(),now=Date.now();s.settings.newLimit=2;s.settings.reviewLimit=1;s.cards[questions[0].id]=schedule(null,'again',now-120000);s.cards[questions[1].id]=schedule(null,'good',now);let queue=dueCards(questions,s,0,now);assert.equal(queue.length,3);assert.equal(queue[0].id,questions[0].id);assert.ok(!queue.some(q=>q.id===questions[1].id));s.activity[dayKey(now)]={total:3,newCards:2,cardReviews:1};assert.equal(dueCards(questions,s,0,now).length,0);});
test('streak permits an active yesterday but breaks on gaps',()=>{const now=new Date(2026,9,8,12).getTime();assert.equal(streak({'2026-10-08':{total:1},'2026-10-07':{total:1}},now),2);assert.equal(streak({'2026-10-07':{total:1},'2026-10-06':{total:1}},now),2);assert.equal(streak({'2026-10-06':{total:1}},now),0);assert.equal(streak({'2026-10-08':{total:0}},now),0);});
test('backup preserves known study data and rejects invalid schedules',()=>{const s=defaults();s.cards[questions[0].id]=schedule(null,'good');s.bookmarks=[questions[0].id,'unknown'];const restored=validateBackup(JSON.parse(JSON.stringify(s)),questions);assert.deepEqual(restored.cards,s.cards);assert.deepEqual(restored.bookmarks,[questions[0].id]);s.cards[questions[0].id].due='bad';assert.throws(()=>validateBackup(s,questions));assert.throws(()=>validateBackup({version:2},questions));});

test('expanded bank preserves original IDs and licensed provenance',async()=>{const {bankOrigins}=await import('../dist/content.js');const {readFile}=await import('node:fs/promises');const audit=JSON.parse(await readFile(new URL('../research/bank-audit.json',import.meta.url)));assert.equal(questions.length,334);assert.equal(questions.filter(q=>!q.origin).length,79);for(let n=1;n<=79;n++)assert.ok(questions.some(q=>q.id==='q'+String(n).padStart(3,'0')));for(const [origin,count]of Object.entries(audit.includedByOrigin)){assert.equal(questions.filter(q=>q.origin===origin).length,count);assert.ok(bankOrigins[origin].license);assert.match(bankOrigins[origin].revision,/^[a-f0-9]{40}$/);}for(const excluded of audit.excluded)assert.ok(!questions.some(q=>q.id===excluded.id));for(const q of questions.filter(q=>q.origin)){assert.ok(tasks[q.task]);assert.equal(q.domain,Number(q.task.split('.')[0]));assert.ok(q.guideReference);assert.ok(q.reviewedOn);if(q.optionExplanations)assert.equal(q.optionExplanations.length,4);for(const option of q.options)assert.doesNotMatch(option,/Both [ABCD] and [ABCD]/i);}});
test('expanded backups retain earlier schedules and bookmarks',()=>{const s=defaults();s.cards.q001=schedule(null,'good');s.bookmarks=['q001','cassani-d1-1.1-001'];s.quiz.q001={attempts:1,correct:1,lastCorrect:true};const restored=validateBackup(s,questions);assert.deepEqual(restored.cards.q001,s.cards.q001);assert.deepEqual(restored.bookmarks,s.bookmarks);});

test('pack toggles pause cards without erasing schedules or quiz history',async()=>{const {enabledQuestions,personalCards}=await import('../dist/packs.js');const s=defaults();assert.equal(enabledQuestions(questions,s).length,79);s.enabledPacks=['cassani'];assert.equal(enabledQuestions(questions,s).length,167);const q=questions.find(q=>q.origin==='cassani');s.cards[q.id]=schedule(null,'good');s.quiz[q.id]={attempts:1,correct:1,lastCorrect:true};s.enabledPacks=[];const restored=validateBackup(s,questions);assert.deepEqual(restored.cards[q.id],s.cards[q.id]);assert.deepEqual(restored.quiz[q.id],s.quiz[q.id]);const id='personal-'+'a'.repeat(64);s.personalDecks=[{id,name:'Mine',enabled:true,cards:[{id:id+'-1',front:'Front',answer:'Back'}]}];s.cards[id+'-1']=schedule(null,'easy');assert.equal(personalCards(s).length,1);s.personalDecks[0].enabled=false;assert.equal(personalCards(s).length,0);assert.deepEqual(validateBackup(s,questions).cards[id+'-1'],s.cards[id+'-1']);});
test('default original bank supports a full weighted mock',async()=>{const {enabledQuestions}=await import('../dist/packs.js');assert.equal(mockSelection(enabledQuestions(questions,defaults())).length,60);});
test('text imports handle quoted tabs/newlines and reject malformed data',async()=>{const {parseDelimited}=await import('../dist/anki-worker.js');assert.deepEqual(parseDelimited('#separator:Tab\n"A\tB"\t"C\nD"\n'),[{id:'0',fields:['A\tB','C\nD']}]);assert.throws(()=>parseDelimited('"unclosed'));});
test('personal-deck backup validation rejects malformed and oversized cards',()=>{const s=defaults(),id='personal-'+'b'.repeat(64);s.personalDecks=[{id,name:'Mine',enabled:true,cards:[{id:id+'-1',front:'Front',answer:'Back'}]}];assert.equal(validateBackup(s,questions).personalDecks[0].cards.length,1);s.personalDecks[0].cards[0].front='x'.repeat(20001);assert.throws(()=>validateBackup(s,questions));});
